---
- name: Deploy hugo blog
  hosts: all
  become: yes

  vars:
    REGISTRY: "{{ lookup('ansible.builtin.env', 'REGISTRY') }}"
    SECRET_KEY: "{{ lookup('ansible.builtin.env', 'SECRET_KEY') }}"
    IMAGE_NAME: "{{ lookup('ansible.builtin.env', 'IMAGE_NAME') }}"
    TAG: "{{ lookup('ansible.builtin.env', 'TAG') }}"
    FULL_IMAGE_NAME: "{{ REGISTRY }}/{{ IMAGE_NAME }}:{{ TAG }}"

  tasks:
    - name: Login to docker registry
      community.docker.docker_login:
        registry: "{{ REGISTRY }}"
        password: "{{ SECRET_KEY }}"
        username: "nologin"
        state: present

    - name: Pull new docker image version
      command: docker pull "{{ FULL_IMAGE_NAME }}"

    - name: Remove docker container
      command: docker container stop "{{ IMAGE_NAME }}"
      ignore_errors: true

    - name: Run docker container
      command: docker run -it -d --rm --name "{{ IMAGE_NAME }}" "{{ FULL_IMAGE_NAME }}"
